hardware/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from stocks import views
# from shops import views

urlpatterns = [
	path('stocks/', views.home, name='home'),
	path('list_items/', views.list_items, name='list_names'),
    path('add_items/', views.add_items, name='add_items'),
    path('update_items/<str:pk>/', views.update_items, name="update_items"),
    path('delete_items/<str:pk>/', views.delete_items, name="delete_items"),
    path('stock_details/<str:pk>/', views.stock_details, name="stock_details"),
    path('issue_items/<str:pk>/', views.issue_items, name="issue_items"),
    path('receive_items/<str:pk>/', views.receive_items, name="receive_items"),
    path('reoder_level/<str:pk>/', views.reoder_level, name="reoder_level"),
    # path('accounts/', include('registration.backends.default.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include('shops.urls', namespace='shops')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/urls.py
from django.urls import path

from .views import (
	index,
	item_list,
	products,
	costomer_list,
	add_to_cart,
	remove_from_cart,
	OrderSummaryView,
	CheckoutView,
	remove_single_from_cart,
	PaymentView,
	AddCouponView,
	RequestRefundView,
	category,
	CashDesk,
	CashDeskprint,
	callbackurl,
	Mpesa,
	callbackurl
	
)


app_name = 'shops'

urlpatterns = [
	path('', index, name = 'index'),
	path('shops/item_list', item_list, name='item_list'), 
	path('checkout/', CheckoutView.as_view(), name='checkout'),
	path('costomer_list', costomer_list, name='costomer_list'),
	path('callbackurl', callbackurl, name='callbackurl'),
	path('product/<int:id>/', products, name='product'),
	path('order-summary', OrderSummaryView.as_view(), name='order-summary'),
	path('add_to_cart/<int:id>/', add_to_cart, name='add_to_cart'),
	path('add-coupan/', AddCouponView.as_view(), name='add-coupan'),
	path('remove_from_cart/<int:id>/', remove_from_cart, name='remove_from_cart'),
	path('remove_single_from_cart/<int:id>/', remove_single_from_cart,
		name='remove_single_from_cart'),
	path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
	path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
	path('category/<int:id>/', category, name="category"),
	path('cashmaney', CashDesk.as_view(), name='cashmaney'),
	path('printcash', CashDeskprint.as_view(), name='printcash'),
		path('mpesa/<payment_option>/', Mpesa.as_view(), name='mpesa'),	
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- <title>Home</title> -->
<!-- <title>{% block head_title %}{% endblock %}</title>
{% block extra_head %}
{% endblock %} -->

<link rel="stylesheet" href=" {% static 'js/jquery-ui-1.12.1/jquery-ui.min.css' %}"/>

<link rel="stylesheet" href="{% static 'js/jquery-ui-1.12.1/jquery-ui.structure.min.css' %}"/>

<link rel="stylesheet" href="{% static 'js/jquery-ui-1.12.1/jquery-ui.theme.min.css' %}"/>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/css/mdb.min.css" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/base.css' %}"/>

<script
			  src="https://code.jquery.com/jquery-2.2.4.min.js"
			  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
			  crossorigin="anonymous"></script>
{% include 'navbar.html' %}


<body>

<div class="">{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role ="alert">
    {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endfor %}
  {% endif %}
</div>


{% block content %}{% endblock content %}

{% block extra_body %}
{% endblock %}

{% include 'footer.html' %}

</body>

<script type="text/javascript">
    $(document).ready(function(){ 
        $('#table').paging({limit:2}); 
    });
</script>

<script src="{% static 'js/jquery-3.5.1.min.js' %}" type="text/javascript"></script>

<script src="{% static 'js/print.min.js' %}" type="text/javascript"></script>

<script src="{% static 'jquery-ui-1.12.1/jquery-ui.min.js' %}" type="text/javascript"></script>

<script src="{% static 'js/pager/paging.js' %}" type="text/javascript"></script>

<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js"> </script>

<script src="{% static 'js/myjs.js' %}" type="text/javascript"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/cashmaney.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<section class="mb-4">

<div class="container">
	<div class="row">
		<div class="col-md-6 mb-4">
		<div class="card">
		<div class="card-body">
<span style="color:  #00c851!important; font-weight: 600; font-size: 2em;">Pay With Cash</span>

		<form method="POST">{% csrf_token %} 
		<div class="md-form mb-5">
		<label for="address" class="">Your Phone Number Must be in that format</label>

		<br/><br/><br/>
	
	</div>


  <button class="btn btn-primary btn-lg btn-block" type="submit">Cash Pay</button>
	</form>
</div>
</div>
</div>
	<!--Grid column-->
<div class="col-md-6 mb-4">
{% include "order_snippet.html" %}

</div>
</section>


{% endblock content %}

templates/category.html
{% extends "base.html" %}


{% block content %}

<div class="category">
	<h1 class="text-center">
		<span>{{ category.name }}</span> Categories
	</h1>
</div>
<div class="container-fluid">
  <div class="row wow fadeIn"> 
	{% for items in item %}
<div class="col-lg-2 col-md-6 mt-4 mb-4">
<div class="card">
 <div class="view overlay">
  <div class="image">
  <img src="{{ items.image.url }}" class="card-img-top" alt=""> 
    <a href="{{ items.get_absolute_url }}">
  
    <div class="mask rgba-white-slight"></div>
  </a>
    <div class="card-body text-center">

<strong>

  <a href="{{ items.get_absolute_url }}" class="dark-grey-text" style="font-weight: bold; font-size: 20px;">{{ items.title }}</a> &nbsp;&nbsp;&nbsp;
<a href="{{ items.category.get_category_absolete_url }}">{{ items.category }}</a>
</strong></h5>
 <h5 class="font-weight-bold blue-text">
   <strong>
  {% if items.discount_price %}
  {{ items.discount_price }}
  {% else %}

    Ksh {{ items.price }}
  {% endif %} </strong>
</h5>
</div>
  </div>
  </div>
  </div>
	</div>
		{% endfor %}

	</div>
</div>


{% endblock content %} 

templates/checkout.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
	<div class="col-md-8">
	<div class="row">
			<div class="card">
				<form method="POST" class="card-body">
					{% csrf_token %}
				
				<label for="address" class="">Your Town/City</label><br/>
					{{ form.town }}<br/>
				<label for="address" class="">Working Phone Number</label><br/>
				{{ form.phone }}<br/>
				<label for="address" class="">ID Number</label><br/>
					{{ form.id_number }}<br/>

	   <hr>
	  <div class="custom-control custom-checkbox">
	   <input {% if form.same_shipping_address.value %}checked{% endif %} type="checkbox" name="same_biliing_address" class="custom-control-input" id="same-address">
	   <label class="custom-control-label" for="same-address">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shipping address is the same as my billing address</label>
	  </div>
	 <div class="custom-control custom-checkbox">
	  <input {% if form.save_info.value %}checked{% endif %} type="checkbox" name="save_info" class="custom-control-input" id="save-info">
	 <label class="custom-control-label" for="save-info">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Save this Information for next time</label>
		</div>
	<hr>
		<div class="d-block my-3">
		{% for value, name in form.fields.payment_option.choices %}
				<div class="custom-control custom-radio">
					<input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input checked required">

					<label class="custom-control-label" for="{{ name }}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ name}}</label>
						</div>
				{% endfor %}
				
			</div>
				
					<button class="btn btn-primary" type="submit">Checkout</button>
				</form>
		</div>


<div class="col-md-4">
	{% include "order_snippet.html" %}

</div>
	</div>
</div>
</div>
{% endblock content %}

templates/costomer_list.html
{% extends "base.html" %}

{% block content %}

<div class="container">
<div class="row">
<h2>Item Customer List</h2>

	<form method="POST" action="">{% csrf_token %}
			{{ form.as_p }}
			<input class="btn btn-primary mybutton" type="submit" value="Search">
	</form>

<div class="table-responsive text-nowrap">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Item title</th>
        <th scope="col">Category</th>
        <th scope="col">Price</th>
        <th scope="col">Discount</th>
        <th scope="col"></th>
        
      </tr>
    </thead>
    <tbody>
    {% for order_item in querySet %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ order_item.title }}</td>
        <td>{{ order_item.category }}</td>
        <td>{{ order_item.price }}</td>

        <td>{{ order_item.discout_price }}</td>
        <td>
        <a href="{{ order_item.get_add_to_cart_url }}" class="btn 	btn-primary btn-md my-0 p">
					Add to Cart
				<i class="fas fa-shopping-cart ml-1"></i>

			</a>
			</td></tr>


      	{% endfor %}
    </tbody>
  </table>

</div>

</div>
</div>
{% endblock content%}

templates/delete_items.html
{% extends "base.html" %}
{% block content %}

<main role="main" class="container">
	<div class="jumbotron">
		<form method="post" action="">
			{% csrf_token %}
			<h1>Are sure you want to delete?</h1><br/>
			<input class="btn btn-danger" type="submit" value="yes">
			<a href="/list_items"><div class="btn btn-primary">Cancel</a>
		</div>
	</div>
	
</main>

{% endblock content %}

templates/footer.html
<!-- Side Modal Top Right -->

<!-- Button trigger modal -->

<!-- Footer -->
<footer class="page-footer font-small pt-4">

  <!-- Footer Elements -->
  <div class="container">

    <!-- Social buttons -->
    <ul class="list-unstyled list-inline text-center">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-gplus mx-1">
          <i class="fab fa-google-plus-g"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-li mx-1">
          <i class="fab fa-linkedin-in"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-dribbble mx-1">
          <i class="fab fa-dribbble"> </i>
        </a>
      </li>
    </ul>
    <!-- Social buttons -->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2021 Copyright:
    <a href="xycoders">xycoders.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/home.html
{% extends "base.html" %}
{% block content %}

<h1>Refuge wise</h1>

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}



<div class="row wow fadeIn">
	{% for item in items %}
	<div class="col-lg-3 col-md-6 mb-4">
		<div class="card">
			<div class="view overlay">
				<img src="{{ item.image.url }}" class="card-img-top" alt="">
				<a>
					<div class="mask rgba-white-slight"></div>
				</a>
			</div>
			<div class="card-body text-center">
				<a href="" class="grey-text">
					<h5>Press</h5>
				</a>
				<h3>
				<strong>
					<a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
				</strong>
				</h3>
			<h4 class="font-weight-blod blue-text">
				<strong>{{ item.price }}</strong>
			</h4>

  <a href="{{ item.category.get_category_absolete_url }}">{{ item.category }}</a>



	</div>
	</div>

	</div>
	{% endfor %}

</div>



{% endblock content %}

templates/mpesa.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<section class="mb-4">

<div class="container">
	<div class="row">
		<div class="col-md-6 mb-4">
		<div class="card">
		<div class="card-body">
<span style="color:  #00c851!important; font-weight: 600; font-size: 2em;">Pay With Mpesa</span>

		<form method="POST">{% csrf_token %} 
		<div class="md-form mb-5">
		<label for="address" class="">Your Phone Number Must be in that format</label>

		<br/><br/><br/>
		{{ form.phone }}
	</div>


  <button class="btn btn-primary btn-lg btn-block" type="submit">Lipa Na M-pesa</button>
	</form>
</div>
</div>
</div>
	<!--Grid column-->
<div class="col-md-6 mb-4">
{% include "order_snippet.html" %}

</div>
</section>


{% endblock content %}

templates/order_snippet.html
 <!-- Heading -->
 <h4 class="d-flex justify-content-between align-items-center mb-3">
<span class="text-muted">Your cart</span>
<span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
</h4>
 <!-- Cart -->
<ul class="list-group mb-3 z-depth-1">
{% for order_item in order.items.all %}
 <li class="list-group-item d-flex justify-content-between lh-condensed">
 <div>
 <h6 class="my-0">{{ order_item.quantity }} * {{ order_item.item.title }}</h6>
<!-- <small class="text-muted">{{ order_item.item.description }}</small> -->
</div>
<span class="text-muted">{{ order_item.get_final_price }}</span>
</li>
{% endfor %}

{% if order.coupon %}
<li class="list-group-item d-flex justify-content-between bg-light">
<div class="text-success">
<h6 class="my-0">Promo code</h6>
<small>{{ order.coupon.code }}</small>
</div>

<span class="text-success">-Ksh{{ order.coupon.amount }}</span>
</li>
{% endif %}
 <li class="list-group-item d-flex justify-content-between">
    <span>Total (Ksh)</span>
  <strong>Shs{{ order.get_total }}</strong>
  </li>
  </ul>
 <!-- Cart -->
 
 <!-- Promo code -->
 {% if DISPLAY_COUPON_FORM %}
<form class="card p-2" action="{% url 'shops:add-coupan' %}" method="POST">
    {% csrf_token %}
  <div class="input-group">
    {{ couponform.code }}
    <div class="input-group-append">
  <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
  </div>
 </div>
</form>
{% endif %}
<!-- Promo code -->
 

templates/printcash.html
{% extends "base.html" %}

{% block content %}
<!--  <div class="modal-dialog modal-full-height modal-center" role="document" id="printJS-form"> -->

<button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">
                Launch demo modal top
</button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">


  <div class="modal-dialog" role="document" id="printJS-form">
    <div class="modal-content">
    
    <div class="modal-content">
  		<div class="modal-body">
  	
  		<div class="container">
  			<div class="row">
  				<div class="col-sm-6" style="font-size: 13px;">
        		P.O.Box 40100, KISUMU<br/>
        		TEL : 072569604 <br/>
        	</div>
    
        <div class="col-sm-6" style="font-size: 13px;">
        	Nyamolori Back Street Mkt<br/>
        	Next To Bhagini Nursery<br/>
        	Stall No 66A<br/>
        </div>

  			</div>
  		</div>
  		<hr/>
  		<center>
        <h4 class="modal-title w-100" id="myModalLabel" style="font-size: 22px; font-style: 600;">
        	COSBEN GENENRAL HARDWARE
        </h4>
        <p style="font-size: 13px;">Dealers in: General Hardware, Plumbing Materials,<br/>Fitting, Electrical Items and Building Materials</p>
     
   		</center>
  
        <table class="table caption-top">
  <caption>
    
  </caption>

  <thead>
    <tr>
      <th scope="col">No</th>
      <th scope="col">Items</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
  {% for order_item in order %}
	{% for print in order_item.items.all %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ print.item }}</td>
      <td>{{ print.quantity }}</td>
      <td>{{ print.get_final_price }}&nbsp;&nbsp;<span class="badge badge-success"> (Discout {{ print.get_amout_saved }} ksh)</span>
      </td>
  </tr>

		{% endfor %}

      <td colspan="5">
      <hr/>
      	<h2> 
      	Total &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      	{{ order_item.get_total }}
      	</h2>
      </td>

  </tbody>
</table>

<hr>
<center style="font-size: 13px;">
<p>For Home Delivery Shop Here
<br/>&nbsp;&nbsp;&nbsp;&nbsp;www.cosben.co.ke<br/>
		&nbsp;&nbsp;&nbsp;&nbsp;Call : 0725696042</p>
</p>
<hr/>
<h6 style="font-size: 13px;">DATE &nbsp;&nbsp;{{ order_item.timestamp }} || <caption>
    served by {{user}}
  </caption></h6><br/>
</center>
{% endfor %}
<p style="font-size: 14px;">Goods Once Sold Will Never Be Returned. THANK YOU</p>
      </div>

     <br/><br/>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

			<button type="button" onclick="printJS('printJS-form', 'html')" class="btn btn-primary">Print Reciept</button>
      </div>
    </div>
  </div>
</div>

{% endblock content%}

templates/request_refund.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<main>
<div class="container">
	<h2>Request Refund</h2>
	<form method="POST">
	{% csrf_token %}

	{{ form|crispy }}

	<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</main>

{% endblock content %}

templates/stock_details.html
{% extends "base.html" %}
{% block content %}

<div class="container">
<div class="jumbotron">
	<div class="header">{{ title }}</div>
		<a href="{% url 'issue_items' queryset.id %}"><div class="btn btn-danger">
			ISSUE THIS ITEM</div></a>

		<a href="{% url 'receive_items' queryset.id %}"><div class="btn btn-primary">
			RECEIVE THIS ITEM</div></a>
			<br/><br/>
		<div class="display_table">
		<table class="table">
			<tr>
				<th>ITEM NAME</th>
				<th>QUATITY</th>
				<th>LAST UPDATE</th>
				<th>RECORDED LEVEL</th>
			</tr>
				<td>{{ queryset.item_name }}</td>
				<td>{{ queryset.quantity }}</td>
				<td>{{ queryset.last_updated }}</td>
				<td>{{ queryset.reoder_level }}</td>
		</table>
	</div>
</div>


{% endblock content %}